### ISSUE TITLE
Redirection Issue: BitPay redirects to "example.com"

### ISSUE THREAD

**Issue by VikBlockEater** [bitpay/php-bitpay-client-v2#103]
I am currently working on BitPays Test environment. I have successfully instantiated BitPay client. After creating the invoice object using BitPay client, I am setting redirectURL, closeURL and autoRedirection attributes. As you can see in below code:

```
// creating BitPay client. Client instantiated successfully
$bitpay = BitPaySDK\Client::create()->withFile(base_path() . '/config/bitpay.json');

// creating invoice
$invoice = $bitpay->createInvoice(new \BitPaySDK\Model\Invoice\Invoice($this>balanceAmount, "USD"));

//setting rediect URL
$invoice->setRedirectURL("https://myappurl.com/wallet");

//setting close URL
$invoice->setCloseURL("https://myappurl.com/wallet");

// enabling auto redirection
$invoice->setAutoRedirect(true);

// get redirection url from invoice
$invoice_redirect_url = $invoice->getURL();

// upon click on livewire component redirect to invoice BitPay URL
return redirect($invoice_redirect_url);

```
In debug mode when I watch the $invoice object. I can see all the above parameters set correctly. 

On the frontend when I click on the component, it redirects me to Bitpay's payment gateway interface. Here comes the issue, when I close the invoice without payment, it redirects me to https://example.com instead of my URL mentioned above.

**Comment by VikBlockEater** [comment]
@BitPay Team, I am officially awaited for your prompt response. I am in middle of a project and stuck at this point. I request you to please expedite.

**Comment by bobbrodie** [comment]
Hi there @VikBlockEater -- we're taking a look at this. Could you share the following?
- If you are using `dev-master` or a tagged version
- Which version of PHP you're on
- Are you using the SDK directly, or are any other frameworks / platforms involved?

Regarding the following:
> On the frontend when I click on the component, it redirects me to Bitpay's payment gateway interface. Here comes the issue, when I close the invoice without payment, it redirects me to https://example.com/ instead of my URL mentioned above.

Could you describe which frontend you're referring to?

**Comment by bobbrodie** [comment]
Hi @VikBlockEater can you confirm if your issue has been resolved? If so, we will close this out. Thank you!

**Comment by bobbrodie** [comment]
Hi @VikBlockEater we're going to close this for now, but if you have any questions please create another issue or reach out to support@bitpay.com.

**Comment by VikBlockEater** [comment]
@bobbrodie Your precious response is awaited.
