### ISSUE TITLE
Unable to call toArray() on Invoice, "Call to a member function toArray() on array"

### ISSUE THREAD

**Issue by karenmt** [bitpay/php-bitpay-client-v2#113]
PHP: 8.1
bitpay/sdk: 7.0.0
When creating an Invoice, then using `->toArray()` on the result, it throws the error `Call to a member function toArray() on array`. Steps to recreate:

```
<?php
namespace YourNamespace\BitpayPHPExample;

error_reporting(E_ALL ^ E_DEPRECATED);

use \BitPaySDK\Model\Currency;
use \BitPaySDK\Model\Invoice\Buyer;
use \BitPaySDK\Model\Invoice\Invoice;

require __DIR__ . '/vendor/autoload.php';

class ExampleInvoice {
  private $client;

  private function setClient($token, $password) {
    $client = \BitPaySDK\Client::create()->withData(
      \BitPaySDK\Env::Test,
      __DIR__ . '/examples/bitpay.key',
      new \BitPaySDK\Tokens(
          $token
      ),
      $password,
      null
    );

    $this->client = $client;
  }

  public function create($token, $password) {
    $this->setClient($token, $password);
    $invoice = new Invoice(50.0, Currency::USD); //Always use the included Currency model to avoid typos
    $invoice->setToken($token);

    $basicInvoice = $this->client->createInvoice($invoice);
    echo 'Invoice URL      : ' . $basicInvoice->getUrl() . PHP_EOL;
    echo 'Invoice JSON URL : ' . 'https://test.bitpay.com/invoices/' . $basicInvoice->getId() . PHP_EOL;
    var_dump($basicInvoice->toArray());
  }
}

$bitpay = new ExampleInvoice();
$bitpay->create('MyToken',"MyPassword");
````

> Uncaught Error: Call to a member function toArray() on array in /home/vagrant/code/bitpaytest/src/BitPaySDK/Model/Invoice/Invoice.php:855
Stack trace:
#0 /home/vagrant/code/bitpaytest/test.php(37): BitPaySDK\Model\Invoice\Invoice->toArray()
#1 /home/vagrant/code/bitpaytest/test.php(42): YourNamespace\BitpayPHPExample\ExampleInvoice->create()
#2 {main}
  thrown in /home/vagrant/code/bitpaytest/src/BitPaySDK/Model/Invoice/Invoice.php on line 855

The error line is `'itemizedDetails'                => $this->getItemizedDetails()->toArray(),`, and `setItemizedDetails` already creates an array.

**Comment by bobbrodie** [comment]
Thanks for reporting this @karenmt. We'll take a look and will release a patch for it. We are actively reviewing all aspects of the SDK and are making improvements to the structure and adding automated tests. We'll report back here with more info.

**Comment by bobbrodie** [comment]
Tracking issue SP-246.

**Comment by bobbrodie** [comment]
@karenmt we are testing a change for this, but I do have a couple notes.
* Running `toArray()` on an Invoice object _before_ sending it to the SDK works as expected
* The issue lies in running `toArray()` on the returned object from the API, like your example

If possible, could you share any information on the intent of calling `toArray()` on the object returned from the API in your example? We are addressing the issue, but are interested in understanding the use case of having the returned data as an array vs. interfacing with the returned object. That insight will help us plan for the future and take it into account for documentation. Thanks!

**Comment by karenmt** [comment]
In that case, I was trying to log the response as a readable array instead of having all of the extra object fluff using print_r. I also plan to store the invoice response in the database as a json string for reference.

**Comment by bobbrodie** [comment]
That sounds good - thank you so much @karenmt ! We'll have an update for this shortly.
