### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by TristanPie** [bitpay/php-bitpay-client-v2#12]
Hi guys,
I there any official release date for a stable version of this new lib ?
Thanks

**Comment by anbugal** [comment]
Hi @TristanPie the new SDK has been release on its version 3.0.1910
https://github.com/bitpay/php-bitpay-client-v2/releases/tag/v3.0.1910

It is also listed on Packagist:
https://packagist.org/packages/bitpay/sdk
