### ISSUE TITLE
Client setPrivateKey

### ISSUE THREAD

**Issue by TristanPie** [bitpay/php-bitpay-client-v2#15]
Hi,
We are using a secure storage system so we don"t have any file for the Client configuration.
In the previous version of the SDK we manage to have a workaround using 
`\Bitpay\Client\Client::setPrivateKey` 
`\Bitpay\Client\Client::setPublicKey`
`\Bitpay\Client\Client::setToken`

But it looks there is no way to initiate the client without using a file.
Did I miss something ? 
Is it possible to add these features ? cause right we are unable to switch to the new client.

Thanks.

**Comment by anbugal** [comment]
Please, follow the [Guide](https://github.com/bitpay/php-bitpay-client-v2/blob/master/GUIDE.md) available on this repository, if you have a private key already, you can use the same.

Please, close the issue if this information was enough to solve your issue, thanks.

**Comment by TristanPie** [comment]
My issue is wit the new version I can initialize the client on two different ways. but both necessary take a File path for the private which I don't have since for the previous version I used \Bitpay\Client\Client::setPrivateKey

**Comment by anbugal** [comment]
I understand the issue now, thanks for the explanation.
As this approach makes sense for this type of integration, this option is now available in the new [Revision](https://github.com/bitpay/php-bitpay-client-v2/releases/tag/v3.1.1910) of the current version just released.
