### ISSUE TITLE
setNotificationURL & setTransactionSpeed issue

### ISSUE THREAD

**Issue by TristanPie** [bitpay/php-bitpay-client-v2#20]
Hi,

It looks like the notification URL and the TransactionSpeed are not setted when creating the invoice.
I created an invoice calling setNotificationURL and setTransactionSpeed("medium");

But I needed to wait 6 blocks confirmation for the invoice to be complete (I can see it on Bitpay website)  which correspond as a 'low'transaction speed. and I didn't receive any IPN callback.

Then when I try to retrieve the invoice doing a $client->getInvoice($id);

The _transactionSpeed and _notificationURL are empty. (var_dump of the Invoice object)

It worked fine with the previous client.

Thanks.

**Comment by anbugal** [comment]
When you run *$client->getInvoice($id);* those keys are never returned on the response and they were not returned with the previous client either.

Regarding the IPN, it is better if you contact [Support](support@bitpay.com) and provide an Invoice ID so we can see better if the IPN was sent. Make sure your IPN listener is not blocking traffic.

Thanks for your contribution.
