### ISSUE TITLE
Way to verify webhook signature

### ISSUE THREAD

**Issue by vrajroham** [bitpay/php-bitpay-client-v2#25]
Is there a way to verify the webhook signature in any way?

I have created a [wrapper for laravel](https://github.com/vrajroham/laravel-bitpay) for bitpay php sdk and I need a way to verify incoming webhook requests.

If someone gets the insights of API of any application, can easily make a fake request to the webhook endpoint if he has prior knowledge.

Thank you so much for the updated release. 👍

**Comment by anbugal** [comment]
Hi @vrajroham,

Thanks for your contribution, I think this will help many Laravel developers out there.
Regarding the IPNs, BitPay does not sign the webhooks and those should be used as a trigger for a signed GET request on the invoice end-point for confirmation.
See more info [Here](https://bitpay.com/api/#notifications-webhooks}

Feel free to contact [Support](support@bitpay.com) if you need further information.

Thanks.

**Comment by vrajroham** [comment]
@anbugal Perfect! 

Thanks for pointing to the correct link for better understanding. I'll take care and will implement the way documented.

Thanks a lot :)
