### ISSUE TITLE
PayoutInstruction Model Incomplete

### ISSUE THREAD

**Issue by phillmorgan28** [bitpay/php-bitpay-client-v2#33]
The payout instruction model does not implement all required fields according to the API documentation.

If the walletProvider field is given, the receiverInfo data must also be set.

> JSON object containing the below nested fields. To be provided if the walletProvider is provided

Will this field / nested fields be added soon?

**Comment by anbugal** [comment]
Hi @phillmorgan28,

This feature will be updated soon, if you are currently using this feature, please contact BitPay.

Thanks for your contribution.
