### ISSUE TITLE
Uncaught exception - Client::Adapter

### ISSUE THREAD

**Issue by Nom-DePlume** [bitpay/php-bitpay-client-v2#34]
if php curl is not installed an exception is generated which is uncaught (unlike for example GMP/bcmath)

PHP Fatal error:  Uncaught Error: Call to undefined function Bitpay\Client\Adapter\curl_init() in ./Bitpay/Client/Adapter/CurlAdapter.php:50

**Comment by anbugal** [comment]
@Nom-DePlume the issue you are reporting does not belong to this repository, for this reason we are closing this issue.
