### ISSUE TITLE
Adding Point of Sale Support 

### ISSUE THREAD

**Issue by Porthorian** [bitpay/php-bitpay-client-v2#36]
It seems there is no support for the Point of Sale facade regarding bitpay. I think this is something that should be added because companies may only use bitpay to create invoices and retrieve invoices for customers. I am not entirely sure how many implications this may cause through out the API wrapper. It doesn't seem like it would be many, but again I do not know the implications of it hence why I am posting this or I would of done it myself.
```
public function getTokenByFacade($facade)
    {
        $token = null;
        switch ($facade) {
            case Facade::Merchant:
                $token = $this->merchant;
                break;
            case Facade::Payroll:
                $token = $this->payroll;
                break;
        }

        if ($token) {
            return $token;
        }

        throw new Exception("given facade does not exist or no token defined for the given facade");
    }
```

**Comment by anbugal** [comment]
Hi @Porthorian for that purpose you can use the lite version of this library:
https://github.com/bitpay/php-bitpay-light-client
