### ISSUE TITLE
Version of ext-json causing issues

### ISSUE THREAD

**Issue by stsepelin** [bitpay/php-bitpay-client-v2#37]
Could you use “ext-json”: “*” instead of 1.5.
Right now it causing issues on PHP 7.4 with latest ext-json.

` Problem 1
    - bitpay/sdk v3.5.2002 requires ext-json ^1.5 -> the requested PHP extension json has the wrong version (7.4.2) installed.
`

**Comment by anbugal** [comment]
Hi @stsepelin thanks for this suggestion. The update is available in the version v3.5.2002.1
