### ISSUE TITLE
CreateInvoice does not set the notificationURL

### ISSUE THREAD

**Issue by ho2problemi** [bitpay/php-bitpay-client-v2#41]
Hi,
running the code in the tests, I am able to set everything of an invoice correctly BUT the notification (setNotificationURL, setFullNotifications, setExtendedNotifications). These fields are not saved in the invoice no matter what I do. I am using PHP 7.4 on IIS if that's of any help.

Thanks

**Comment by anbugal** [comment]
Hi @ho2problemi 

The notificationURL is being set correctly, you won't see it when creating or retrieving an invoice for safety reasons as we do not encrypt our webhook notifications (IPN).
You will see the IPNs coming in as soon as the invoice is payed.

Remember to compare the status of a given IPN with the status of its invoice by using GetInvoice.

Please, avoid using ngrok.io for webhook testing as this service won't work with the BitPay's IPNs.

Thanks for your contribution.
