### ISSUE TITLE
PHP 7.4 deprecated error

### ISSUE THREAD

**Issue by ho2problemi** [bitpay/php-bitpay-client-v2#42]
Hello,
when I run the PHP code on its own, it works correctly. When instead I try to integrate it with the framework I built, I get the following error on the JsonMapper, which looks like it's due to the PHP version (it's 7.4.4):

Custom Exception Handler : BitPaySDK\Exceptions\InvoiceQueryException: BITPAY-INVOICE-GET: Failed to retrieve invoice-> failed to deserialize BitPay server response (Invoice) : Custom Error Handler:
Error Num: 8192 / Error Description: Function ReflectionType::__toString() is deprecated
File:C:\web\www\app\vendor\bitpay\sdk\src\BitPaySDK\Util\JsonMapper\JsonMapper.php on line 394

**Comment by anbugal** [comment]
Hi @ho2problemi 

This issue has been fixed on the version 3.6.2005.

Thanks for your feedback and contribution.

**Comment by ho2problemi** [comment]
I tested and it works correctly now, thanks!
