### ISSUE TITLE
Upgrade guide?

### ISSUE THREAD

**Issue by gsaqui** [bitpay/php-bitpay-client-v2#44]
I'm wondering if there is an upgrade guide I can follow to move from the old version of php-bitpay-client (https://github.com/bitpay/php-bitpay-client) to the newest version.  One issue I'm having currently is the PrivateKey is serialized for a class that has been refactored in the new lib to `BitPayKeyUtils\KeyHelper\PrivateKey` when it used to be `Bitpay\PrivateKey`

**Comment by anbugal** [comment]
Hi @gsaqui,

You should be able to use the same private key and tokens that you already have but I recommend to generate a new key, request a new token, approve it in your BitPay account and revoke que existing one.

To generate a new Private Key and Token please, follow the instructions and run the [ConfigGenerator](https://github.com/bitpay/php-bitpay-client-v2/blob/master/examples/ConfigGenerator.php)

**Comment by gsaqui** [comment]
Hi @anbugal 

You're right it's a better option to generate new keys.  I'll go ahead and do that and close this issue.  Thanks for taking the time to get back to me.
