### ISSUE TITLE
Error "invalid signature" while creating invoice in bitpay. 

### ISSUE THREAD

**Issue by koushikids** [bitpay/php-bitpay-client-v2#47]
My signature creating code below. I have got this response "1Teq5NscTgkgxW6dJTw2EyjqkENEnHVcRhm4" finally, but bitpay throws invalid signature error.

function hexStringToByteString($hexString){
    $len=strlen($hexString);
    $byteString="";
    for ($i=0;$i<$len;$i=$i+2){
        $charnum=hexdec(substr($hexString,$i,2));
        $byteString.=chr($charnum);
    }
return $byteString;
}
// BCmath version for huge numbers
function bc_arb_encode($num, $basestr) {
    if( ! function_exists('bcadd') ) {
        Throw new Exception('You need the BCmath extension.');
    }
    $base = strlen($basestr);
    $rep = '';
    while( true ){
        if( strlen($num) < 2 ) {
            if( intval($num) <= 0 ) {
                break;
            }
        }
        $rem = bcmod($num, $base);
        $rep = $basestr[intval($rem)] . $rep;
        $num = bcdiv(bcsub($num, $rem), $base);
    }
    return $rep;
}

function bc_arb_decode($num, $basestr) {
    if( ! function_exists('bcadd') ) {
        Throw new Exception('You need the BCmath extension.');
    }
    $base = strlen($basestr);
    $dec = '0';
    $num_arr = str_split((string)$num);
    $cnt = strlen($num);
    for($i=0; $i < $cnt; $i++) {
        $pos = strpos($basestr, $num_arr[$i]);
        if( $pos === false ) {
            Throw new Exception(sprintf('Unknown character %s at offset %d', $num_arr[$i], $i));
        }
        $dec = bcadd(bcmul($dec, $base), $pos);
    }
    return $dec;
}
// base 58 alias
function bc_base58_encode($num) {   
    return bc_arb_encode($num, '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz');
}
function bc_base58_decode($num) {
    return bc_arb_decode($num, '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz');
}
//hexdec with BCmath
function bc_hexdec($num) {
    return bc_arb_decode(strtolower($num), '0123456789abcdef');
}
function bc_dechex($num) {
    return bc_arb_encode($num, '0123456789abcdef');
}
// step 1
$publickey='6Q1mKdNWhcfZjBVuCvGU1ijYtYuhh9gnKqw8WUe4gDob';
$step1=hexStringToByteString($publickey);
$step2=hash("sha256",$step1);
// step 3
$step3=hash('ripemd160',hexStringToByteString($step2));
// step 4
$step4="0F02".$step3;
// step 5
$step5=hash("sha256",hexStringToByteString($step4));
// step 6
$step6=hash("sha256",hexStringToByteString($step5));
// step 7
$checksum=substr($step6,0,8);
// step 8
$step8=$step4.$checksum;
// step 9
$step9="1".bc_base58_encode(bc_hexdec($step8));
echo "step9 ".$step9;

**Comment by anbugal** [comment]
Hi @koushikids,

Are you trying to build your own SDK? why don't you use the built in functionalities for that?

**Comment by koushikids** [comment]
Hi @anbugal 
 i have tried many libraries and functionalities but nothing working. this looks very clear so i have choosed this.

**Comment by anbugal** [comment]
The best option to integrate with BitPay is to use the official SDKs, so this is the right choice.
Please describe your issue as what described before does not give a clear overview of an issue.

**Comment by koushikids** [comment]
I have tried to generate x-signature for create bitpay invoice, i used above code generate x-signature, used this signature code in postman and sent request , it shows   {   "error": "Invalid signature"  } error. i have tried many SDKs but not working.

**Comment by anbugal** [comment]
I am not talking about trying with "many SDKs". This functionality is integrated in the SDK so you do not need to code above.
Please, follow the steps explained in the [GUIDE](https://github.com/bitpay/php-bitpay-client-v2/blob/master/GUIDE.md)

**Comment by anbugal** [comment]
I am closing this issue as it is not relevant in this repository.
