### ISSUE TITLE
Php8.1 issues 

### ISSUE THREAD

**Issue by githubuser990022** [bitpay/php-bitpay-client-v2#79]
Hello,

I have been trying to replace the [bitpay/sdk-light](https://packagist.org/packages/bitpay/sdk-light) with the full version dependency since there is no support of php 8.1 on the light version and i came up with a few issues. 

I have generated the my config file using the [BitPay Config Generator](https://github.com/bitpay/php-bitpay-client-v2/blob/master/examples/ConfigGenerator.php)

I only tried to create an object using  
`BitPaySDK\Client::create()->withFile(['PATH TO THE FILE']);`

Received the following error:
`Deprecated: BitPayKeyUtils\Util\Point implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/html/vendor/bitpay/key-utils/src/BitPayKeyUtils/Util/Point.php on line 10`

`Deprecated: BitPayKeyUtils\KeyHelper\PrivateKey implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/html/vendor/bitpay/key-utils/src/BitPayKeyUtils/KeyHelper/PrivateKey.php on line 15`

`Deprecated: BitPayKeyUtils\KeyHelper\PublicKey implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/html/vendor/bitpay/key-utils/src/BitPayKeyUtils/KeyHelper/PublicKey.php on line 14`

Thanks in advance

**Comment by anbugal** [comment]
Please follow the setup guide for the lite SDK:
https://github.com/bitpay/php-bitpay-light-client/blob/master/GUIDE.md

**Comment by githubuser990022** [comment]
Thank you for your response, but i have followed the guide of the lite SDK which i have already been using.

On the requirements of the light 
php: ^7.1

Will you have an update to it for php 8? If not please review my issue with the issue that have been occurred while using the full sdk bitpay.
