### ISSUE TITLE
Php 8.1 Issue

### ISSUE THREAD

**Issue by yikarus18** [bitpay/php-bitpay-client-v2#83]
Recentrly there was an update to make this repository work on php 8.1, however when downloading repository through composer I'm still getting the error of skd requires 7.1 and my version (8.1.4) is no satisfiable, what am I missing on the installation?

**Comment by ppatidar2021** [comment]
@yikarus18 Upgraded php version to 8.1.  Can you please test it.

**Comment by bobbrodie** [comment]
Code in the master branch has been updated to work with PHP 8.1 and all deprecations addressed. We are running through some final tests and will tag / release.
