### ISSUE TITLE
Capitalization issue in "proxy" key spelling

### ISSUE THREAD

**Issue by VikBlockEater** [bitpay/php-bitpay-client-v2#99]
In ConfigGenerator.php, the key name "proxy" (in line# 216 and 225 <commit# [ef2ca72]>) must be written as "Proxy" (note the "P" is in caps). Otherwise, when instantiating the GuzzleHttp\Client the $proxy variable will be empty. In that case no proxy will be implemented.

**Comment by bobbrodie** [comment]
Addressed in master, will be part of 7.2.0. Thanks!
